1. What are data structures, and why are they important?

Ans - Data Structures are methods for organizing and storing data effectively. They are important because they help  in managing and retrieving data in most efficient manner, making programs faster and easier to manage.

2. Explain the difference between mutable and immutable data types with examples?

Ans - Mutable Data types - These are the data types which can be modified or changed after they are created.
For example : List, dict, set
Immutable Data types - These are data types which cannot be changed after creation.
For example : Tuple

3. What are the main differences between lists and tuples in Python?

Ans - Lists - Lists are Mutable data structure.
They use more memory.
Example :  mylist = [1,2,3,4]

Tuples - Tuples are Immutable type of data structure.
They use less memory.
Example : mytuple = (1,2,3,4)

4. Describe how dictionaries store data.

Ans - Dictionaries store data in key-value pairs using a hash table, which allows fast lookups.

5. Why might you use a set instead of a list in Python?

Ans - Sets are unordered which stores only unique elements, these are useful to remove duplicates and fast membership tests.

6. What is a string in Python, and how is it different from a list?

Ans - String is a Immutable sequence of characters whereas list is a mutable sequence of elements. List can contain different data types.

Example of string : "Akanksha"
Example of List : ["A","B", 3,4]

7. How do tuples ensure data integrity in python?

Ans - With its Immutable nature, tuple ensures integrity of data preventing accidental changes and ensures that data remains constant.

8. What is a hash table, and how does it relate to dictionaries in Python?

Ans - Hash table maps keys to values using hash function. Dictionaries in python are implemented using hash tables.

9. Can lists contain different data types in python?

Ans - Yes, lists can contain different data types.
For example : my_list = [1, 3.14, "Akanksha", True, "a"]

10. Explain why strings are immutable in Python.

Ans - Strings are immutable which makes them secure by preventing accidental modifications.

11. What advantages do dictionaries offer over lists for certain tasks?

Ans - Dictionaries stores data in key-value pairs for clear relationships whereas lists stores values by index only.

Dictionaries can be accessed using unique and meaningful keys while lists can be accessed by index which can be error-prone.

Dictionaries provide more descriptive and readable codes as compared to lists.

12. Describe a scenario where using a tuple would be preferable over a list.

Ans - When data needs to be secured and do not need any modifications after creation like coordinates, days of the week.

13. How do sets handle duplicate values in Python?

Ans - Sets automatically removes duplicate values.

14. How does the “in” keyword work differently for lists and dictionaries?

Ans- In Lists, "in" keyword is used to check if an element is present.

In dictionaries, "in" keyword is used to check if a key is present.

15. Can you modify the elements of a tuple? Explain why or why not.

Ans - Tuples are immutable hence the elements present in tuple cannot be modified.

16. What is a nested dictionary, and give an example of its use case?

Ans - A dictionary inside another dictionary.
Example:  {'student': {'name': 'Akanksha', 'age': 25}}

17. Describe the time complexity of accessing elements in a dictionary.

Ans - Average case is O(1) due to hash table implementation.

18.  In what situations are lists preferred over dictionaries?

Ans - When order is required and accesing data using index is needed.

19. Why are dictionaries considered unordered, and how does that affect data retrieval?

Ans - Dictionaries previously didn't preserve order but now they do. It affects data retrieval because there is no indexing and the data is accessed by key and not position.

20.  Explain the difference between a list and a dictionary in terms of data retrieval.

Ans - In list, data could be accessed by Index while in dictionary, data could be accessed by Key.

Practical Questions

1. Write a code to create a string with your name and print it.

In [3]:
Name = ("Akanksha")
print(Name)

Akanksha

2. Write a code to find the length of the string "Hello World".

In [4]:
print(len("Hello World"))

11

3. Write a code to slice the first 3 characters from the string "Python Programming".

In [9]:
String = ("Python Programming")
print(String[0:3])

Pyt

4.  Write a code to convert the string "hello" to uppercase.

In [10]:
S1 = "Hello"
S1.upper()

'HELLO'

5. Write a code to replace the word "apple" with "orange" in the string "I like apple".

In [11]:
S2 = "I like apple"
S2.replace("apple","orange")

'I like orange'

6. Write a code to create a list with numbers 1 to 5 and print it.

In [13]:
Numbers = [1,2,3,4,5]
print(Numbers)

[1, 2, 3, 4, 5]

7.  Write a code to append the number 10 to the list [1, 2, 3, 4].

In [14]:
numbers = [1,2,3,4]
numbers.append(10)
print(numbers)

[1, 2, 3, 4, 10]

8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].

In [15]:
lst = [1,2,3,4,5]
lst.remove(3)
print(lst)

[1, 2, 4, 5]

 9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].

In [17]:
mylist = ['a','b','c','d']
mylist[1]

'b'

10.  Write a code to reverse the list [10, 20, 30, 40, 50].

In [20]:
lst = [10,20,30,40,50]
lst.reverse()
print(lst)

[50, 40, 30, 20, 10]

11. Write a code to create a tuple with the elements 100, 200, 300 and print it.

In [21]:
t1 = (100,200,300)
print(t1)

(100, 200, 300)

12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').

In [22]:
colours = ('red','green','blue','yellow')
colours[-2]

'blue'

13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).

In [23]:
tup = (10,20,5,15)
min(tup)

5

14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [24]:
animals = ('dog','cat','rabbit')
animals.index('cat')

1

 15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

In [28]:
fruits = ("apple","kiwi","orange")
"kiwi" in fruits

True

 16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.

In [31]:
s1 = {'a','b','c'}
print(s1)

{'b', 'c', 'a'}

17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

In [33]:
my_set = {1,2,3,4,5}
my_set.clear()
print(my_set)

set()

18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.

In [36]:
s1 = {1,2,3,4}
s1.remove(4)
print(s)

{1, 2, 3}

19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.

In [39]:
s1 = {1,2,3}
s2 = {3,4,5}
print(s1.union(s2))

{1, 2, 3, 4, 5}

20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

In [44]:
s1 = {1,2,3}
s2 = {2,3,4}
print(s1 & s2)

{2, 3}

 21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

In [47]:
D = {"name":"Akanksha","age":25,"city":"Faridabad"}
print(D)

{'name': 'Akanksha', 'age': 25, 'city': 'Faridabad'}

 22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

In [49]:
d = {'name':'John','age':25}
d['country'] = 'USA'
print(d)

{'name': 'John', 'age': 25, 'country': 'USA'}

 23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

In [50]:
d1 = {'name':'Alice','age':30}
d1['name']

'Alice'

24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

In [52]:
d2 = {'name': 'Bob', 'age': 22, 'city': 'New York'}
del d2['age']
print(d2)

{'name': 'Bob', 'city': 'New York'}

 25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

In [55]:
d3 = {'name': 'Alice', 'city': 'Paris'}
'city' in d3

True

26. Write a code to create a list, a tuple, and a dictionary, and print them all.

In [56]:
my_list = [1,2,3,4]
my_tuple = (5,6,7,8)
my_dict = {"a":1,"b":2,"c":3}
print(my_list,my_tuple,my_dict)

[1, 2, 3, 4] (5, 6, 7, 8) {'a': 1, 'b': 2, 'c': 3}

 27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.

In [63]:
import random
lst = random.sample(range(1,101),5)
lst.sort()
print(lst)

[2, 24, 53, 75, 95]

28. Write a code to create a list with strings and print the element at the third index.

In [64]:
colours = ["Pink","Red","Yellow","Green","Blue"]
print(colours[3])

Green

 29. Write a code to combine two dictionaries into one and print the result.

In [66]:
d1 = {'a':1,'b':2,'c':3}
d2 = {'d':4,'e':5,'f':6}
d1.update(d2)
print(d1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

30. Write a code to convert a list of strings into a set.

In [67]:
my_list = ["red","green","blue","white"]
my_set = set(my_list)
print(my_set)

{'red', 'green', 'blue', 'white'}